BookLab/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from Users.views import home_view, signup_view, activation_sent_view, activate, login_view, logout_view, password_reset, reset
from Books.views import distance, store_page, product_creation_page, render_single
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('signup/', signup_view, name="signup"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('distance/', distance, name="distance"),
    path('passwordreset/', password_reset, name="password_reset"),
    path('reset/<slug:uidb64>/<slug:token>/', reset, name="reset"),
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('create/', product_creation_page, name="create"),
    path('store/', store_page, name="store"),
    path('book/<str:uid>', render_single, name="single"),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Books/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
# Create your models here.
def localtime():
    return timezone.localtime(timezone.now())

class Book(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller')
    uid = models.CharField(default=uuid.uuid4, max_length=50)
    sold = models.BooleanField(default=False)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name='buyer', null=True)
    name = models.CharField(max_length=30, blank=False, null=True)
    price = models.CharField(max_length=10, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    isbn = models.CharField(max_length=30, blank=True)
    pre_tags = models.TextField(blank=True, null=True)
    post_tags = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    dimensions = models.TextField(blank=True, null=True)
    publishing_date = models.DateTimeField(default=localtime)
    post_date = models.DateTimeField(default=localtime)
    update_date = models.DateTimeField(default=localtime)

class ImageBook(models.Model):
    caption = models.CharField(max_length=255, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    default = models.BooleanField(default=False)

class Listing(models.Model):
    isbn = models.CharField(max_length=30, blank=False)
    number = models.CharField(max_length=10, blank=False)
    description = models.TextField(blank=False)

class ComboBook(models.Model):
    group = models.CharField(max_length=50, blank=False)

class ReportedBooks(models.Model):
    seller = models.OneToOneField(User, on_delete=models.CASCADE, related_name='reportedseller')
    reporter = models.OneToOneField(User, on_delete=models.CASCADE, related_name='reporter')
    book = models.OneToOneField(Book, on_delete=models.CASCADE, related_name='book')

Books/forms.py
from django import forms
from .models import Book, ImageBook

class BookForm(forms.ModelForm):
    name = forms.CharField(max_length=30)
    isbn = forms.CharField(max_length=30, label="ISBN number")
    location = forms.CharField(max_length=60,widget = forms.HiddenInput())

    class Meta:
        model = Book
        fields = ('name', 'isbn', 'location')


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    caption = forms.CharField(max_length=255)

    class Meta:
        model = ImageBook
        fields = ('image', 'caption',)

Books/views.py
from django.shortcuts import render, redirect, HttpResponse

# Create your views here.
from math import radians, cos, sin, asin, sqrt
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import *
from .forms import *

@csrf_exempt
def distance(request):
    # The math module contains a function named
    # radians which converts from degrees to radians.
    if request.is_ajax and request.method == "POST":
        data = request.POST
        lat1 = float(data.get('lat1', None))
        lon1 = float(data.get('lon1', None))#data['lon1']
        lat2 = float(data.get('lat2', None))#data['lat2']
        lon2 = float(data.get('lon2', None))
        print(lat1,lon1,lat2,lon2)#data['lon2']
        lon1 = radians(lon1)
        lon2 = radians(lon2)
        lat1 = radians(lat1)
        lat2 = radians(lat2)
        print(lat1, lon1, lat2, lon2)
        # Haversine formula
        dlon = lon2 - lon1
        dlat = lat2 - lat1
        print(dlon, dlat)
        a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2

        c = 2 * asin(sqrt(a))
        print(c)

        # Radius of earth in kilometers. Use 3956 for miles
        r = 6371
        data = {
            'dist': str(c * r)
        }
        # calculate the result
        #print(JsonResponse(data))
        return JsonResponse(data)
    else:
        return redirect('home')

def store_page(request):
    books = Book.objects.filter(sold=False)
    return render(request, 'ManyBooks.html', {'books': books})

def render_single(request,uid):
    book = Book.objects.filter(uid=uid)
    if book:
        book = book[0]
        return render(request, 'OneBook.html', {'book': book})
    return HttpResponse('Bad Request')


def product_creation_page(request):
    if request.method == 'POST':

        formset = ImageForm(request.POST, request.FILES)
        postForm = BookForm(request.POST)
        # formset = ImageFormSet(request.POST, request.FILES,
        #                        queryset=Images.objects.none())
        if not postForm.is_valid():
            print('invalid 1')
        if not formset.is_valid():
            print('invalid 2')
        if postForm.is_valid() and formset.is_valid():
            name = postForm.cleaned_data['name']
            isbn = postForm.cleaned_data['isbn']
            location = str(postForm.cleaned_data['location'])
            #print(eval(location))
            book = Book(seller=request.user, name=name, isbn=isbn, location=location)
            book.save()

            # for form in formset.cleaned_data:
            #     # this helps to not crash if the user
            #     # do not upload all the photos
            #     if form:
            image = formset.cleaned_data['image']
            caption = formset.cleaned_data['caption']
            photo = ImageBook(book=book, image=image, caption=caption)
            photo.save()
            # use django messages framework
            # messages.success(request,
            #                  "Yeeew, check it out on the home page!")
            return redirect("store")

    else:
        postForm = BookForm()
        formset = ImageForm()
    return render(request, 'list_book.html',
                  {'postForm': postForm, 'formset': formset})

Books/templates/ManyBooks.html
{% load custom_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel Images</title>

      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
      </script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
      </script>
</head>
<body>

    {% for book in books %}
            <div class="col-md-4">
                    <a class="link-success" href="{% url 'single' uid=book.uid %}">{{ book.name }}</a>
                     <img src="{{ book.imagebook_set.all.0.image.url }}" class="img-responsive" style="width: 100px; float: left; margin-right: 10px;" />

                <script>
                    console.log({{book.location|get_list}});
                </script>
            </div>
    {% endfor %}
</body>
</html>

Books/templates/OneBook.html
{% load custom_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel Images</title>

      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
      </script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
      </script>
</head>
<body>
            <div class="col-md-4">
                    {{ book.name }}
                     <img src="{{ book.imagebook_set.all.0.image.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
                <button onclick="getLocation({{book.location|get_list}});">Try It</button>
                <script>
                    console.log({{book.location|get_list}});
                </script>
            </div>
<p id="demo1">Book location: {{book.location|get_list}}</p>
<p id="demo"></p>
<p id="dist"></p>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
var x = document.getElementById("demo");

function getLocation(locatio) {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function (position) {
    var lat2 = locatio[0];
    var lon2 = locatio[1];
    showPosition(position, lat2, lon2);
  });
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position,lat2,lon2) {
  x.innerHTML = "Latitude: " + position.coords.latitude +
  "<br>Longitude: " + position.coords.longitude;
  var latlon = position.coords.latitude + "," + position.coords.longitude;
     $.ajax({
        type: 'POST',
        url: '{% url 'distance' %}',
        data: {
                    'lat1':position.coords.latitude,
                    'lat2':lat2,
                    'lon1':position.coords.longitude,
                    'lon2':lon2
        },
        dataType: 'json',
        success: function (data) {
          if (data.dist) {
            $( '#dist' ).text(data.dist+" km");
          }
        }
      });
}
</script>
</body>
</html>

Books/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hello
<a href="{% url 'logout' %}">Logout</a>

<div id="mapholder"></div>

<p>Click the button to get your coordinates.</p>

<button onclick="getLocation()">Try It</button>

<p id="demo"></p>
<p id="dist"></p>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
var x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  x.innerHTML = "Latitude: " + position.coords.latitude +
  "<br>Longitude: " + position.coords.longitude;
  var latlon = position.coords.latitude + "," + position.coords.longitude;
     $.ajax({
        type: 'POST',
        url: '{% url 'distance' %}',
        data: {
          'lat1':position.coords.latitude,
                  'lat2':position.coords.longitude,
                   'lon1':0.0,
                    'lon2':0.0
        },
        dataType: 'json',
        success: function (data) {
          if (data.dist) {
            $( '#dist' ).text(data.dist+" km");
          }
        }
      });
}
</script>
<!--<script>-->
<!--var x = document.getElementById("demo");-->
<!--window.onload =function(){ getLocation() };-->
<!--getLocation() {-->
<!--  if (navigator.geolocation) {-->
<!--    navigator.geolocation.watchPosition(showPosition);-->
<!--  } else {-->
<!--    x.innerHTML = "Geolocation is not supported by this browser.";-->
<!--  }-->
<!--}-->

<!--function showPosition(position) {-->
<!--  var latlon = position.coords.latitude + "," + position.coords.longitude;-->

<!--  var img_url = "https://maps.googleapis.com/maps/api/staticmap?center=-->
<!--  "+latlon+"&zoom=14&size=400x300&sensor=false&key=AIzaSyBoD_kXJr4oVj9GMMEg1IGoiC31PqhbHEY";-->
<!--  console.log(img_url);-->

<!--  document.getElementById("mapholder").innerHTML = "<img src='"+img_url+"'>";-->
<!--}-->
<!--</script>-->
<!--$.ajax(-->
<!--    {-->
<!--        type:"POST",-->
<!--        url: "/distance",-->
<!--        data:{-->
<!--                 lat1:position.coords.latitude,-->
<!--                  lat2:position.coords.longitude,-->
<!--                   lon1:0.0,-->
<!--                    lon2:0.0-->
<!--        },-->
<!--        success: function( data )-->
<!--        {-->
<!--            $( '#dist' ).text(data);-->
<!--        }-->
<!--     })-->
</body>
</html>

Books/templates/list_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
    {{ postForm.as_p }}
    {{ formset.as_p }}
    <input type="submit" value="Submit">
</form>
<button onclick="getLocation()">Try It</button>


<p id="demo"></p>
<p id="dist"></p>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
var x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
document.getElementById("id_location").value = [position.coords.latitude,position.coords.longitude];
}
</script>
</body>
</html>